# Generated by Django 4.1.2 on 2023-01-07 22:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HelbManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='resources',
            field=models.ManyToManyField(related_name='resources', through='HelbManager.ProjectResource', to=settings.AUTH_USER_MODEL),
        ),
    ]
